language:
    - java

services:
    - mysql

jdk:
    - oraclejdk8
    - openjdk7

before_install:
    - mysql -u root < DeliberationsScript.sql

script:
    - mvn clean test

cache:
    directories:
        - $HOME/.m2   # Cache para las dependencias de maven

dist:
    - trusty

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam
